services:
  - type: web
    name: dataviz-pro-backend
    env: node
    region: ohio  # You can change this to your preferred region
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    plan: free  # Change to your desired plan
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # Add your MongoDB URI in Render dashboard
      - key: JWT_SECRET
        sync: false  # Add your JWT secret in Render dashboard
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false 